services:
  - type: static_site
    name: cafeteria-v2-guarincito
    repo: https://github.com/Mr-Felipe/cafeteria-v2-guarincito
    branch: master
    buildCommand: npm install && npm run build:prod
    staticPublishPath: ./dist/app/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
